#pragma once

#include <filesystem>
#include <string>
#include <set>
#include <memory>

/**
 * @class FrameViewRunner
 * @brief Manages FrameView lifecycle for automated performance testing
 * 
 * This class handles:
 * - Auto-detecting FrameView installation
 * - Creating an isolated copy for testing
 * - Configuring output directory
 * - Starting/stopping FrameView processes
 * - Finding CSV log files generated by FrameView
 * 
 * Usage:
 *   {
 *       std::string error;
 *       auto frameView = FrameViewRunner::create(error);
 *       if (!frameView) {
 *           // Handle error
 *       }
 *       
 *       // Run tests...
 *       auto csv = frameView->findLatestCsvForApp("MyGame.exe");
 *       frameView->notifyCsvConsumed(csv);
 *   }  // Destructor cleans up FrameView processes
 */
class FrameViewRunner
{
public:
    /**
     * @brief Create and initialize a FrameViewRunner
     * 
     * Performs the full initialization sequence:
     * 1. Kills any existing FrameView processes
     * 2. Finds FrameView installation (registry or common paths)
     * 3. Copies FrameView to temp directory for isolation
     * 4. Configures Settings.ini with output directory
     * 5. Launches FrameView_x64.exe
     * 
     * @param outError Populated with a description on failure
     * @return A valid FrameViewRunner, or nullptr on failure
     */
    static std::unique_ptr<FrameViewRunner> create(std::string& outError);
    
    /**
     * @brief Destructor - kills FrameView processes
     */
    ~FrameViewRunner();
    
    // Non-copyable, non-movable
    FrameViewRunner(const FrameViewRunner&) = delete;
    FrameViewRunner& operator=(const FrameViewRunner&) = delete;
    FrameViewRunner(FrameViewRunner&&) = delete;
    FrameViewRunner& operator=(FrameViewRunner&&) = delete;
    
    /**
     * @brief Get the detected FrameView installation path
     * @return Path to FrameView installation
     */
    std::filesystem::path getInstallPath() const { return m_installPath; }
    
    /**
     * @brief Get the detected FrameView version
     * @return Version string, or empty if not determined
     */
    std::string getVersion() const { return m_version; }
    
    /**
     * @brief Find the latest CSV file generated for a specific application
     * @param appName The application name to search for (e.g., "Cyberpunk2077.exe")
     * @return Path to the CSV file, or empty path if not found
     * 
     * Searches the output directory for CSV files containing the app name.
     * Returns the most recently modified file that hasn't been consumed.
     */
    std::filesystem::path findLatestCsvForApp(const std::string& appName);
    
    /**
     * @brief Mark a CSV file as consumed so it won't be returned again
     * @param path Path to the CSV file to mark as consumed
     * 
     * After consuming a CSV, subsequent calls to findLatestCsvForApp() 
     * will not return that file, allowing multiple test runs with the 
     * same application to each get their own CSV.
     */
    void notifyCsvConsumed(const std::filesystem::path& path);

private:
    FrameViewRunner() = default;

    std::filesystem::path findFrameViewInstallation();
    void killFrameViewProcesses();
    bool prepareFrameViewCopy(const std::filesystem::path& sourceDir, std::string& outError);
    bool modifyIniFile(std::string& outError);
    bool launchFrameView(std::string& outError);

    std::filesystem::path m_installPath;         ///< Original FrameView installation path
    std::string m_version;                       ///< FrameView version
    std::filesystem::path m_frameViewCopyPath;   ///< Path to copied FrameView
    std::filesystem::path m_outputDirectory;     ///< Where CSVs are written
    std::set<std::filesystem::path> m_consumedCsvs;  ///< CSVs already consumed
};
