#pragma once

#include <filesystem>
#include <string>
#include <set>
#include <mutex>
#include <memory>

/**
 * @class FrameViewRunner
 * @brief Manages FrameView's capture engine for automated performance testing
 *
 * Rather than launching the FrameView_x64.exe GUI/orchestrator (which crashes
 * in its WndProc on some configurations), this class drives FrameView's
 * underlying ETW capture engine, PresentMon_x64.exe, directly and in-place from
 * the installation's bin\ directory. PresentMon runs resident in multi-CSV mode,
 * writing one CSV per captured process into the output directory.
 *
 * This class handles:
 * - Auto-detecting FrameView installation
 * - Configuring output directory
 * - Starting/stopping PresentMon (FrameView's capture engine)
 * - Finding CSV log files generated by PresentMon
 *
 * NOTE: PresentMon's ETW consumer requires administrator rights, so slVerdict
 * must run elevated for capture to produce CSVs.
 *
 * Usage:
 *   {
 *       std::string error;
 *       auto frameView = FrameViewRunner::create(error);
 *       if (!frameView) {
 *           // Handle error
 *       }
 *       
 *       // Run tests...
 *       auto csv = frameView->findLatestCsvForApp("MyGame.exe");
 *       frameView->notifyCsvConsumed(csv);
 *   }  // Destructor cleans up FrameView processes
 */
class FrameViewRunner
{
public:
    /**
     * @brief Create and initialize a FrameViewRunner
     * 
     * Performs the full initialization sequence:
     * 1. Kills any existing FrameView/PresentMon processes
     * 2. Finds FrameView installation (registry or common paths)
     * 3. Prepares the output directory (and clears stale CSVs)
     * 4. Launches PresentMon_x64.exe (FrameView's capture engine) directly
     *
     * @param outError Populated with a description on failure
     * @return A valid FrameViewRunner, or nullptr on failure
     */
    static std::unique_ptr<FrameViewRunner> create(std::string& outError);
    
    /**
     * @brief Destructor - kills FrameView processes
     */
    ~FrameViewRunner();
    
    // Non-copyable, non-movable
    FrameViewRunner(const FrameViewRunner&) = delete;
    FrameViewRunner& operator=(const FrameViewRunner&) = delete;
    FrameViewRunner(FrameViewRunner&&) = delete;
    FrameViewRunner& operator=(FrameViewRunner&&) = delete;
    
    /**
     * @brief Get the detected FrameView installation path
     * @return Path to FrameView installation
     */
    std::filesystem::path getInstallPath() const { return m_installPath; }
    
    /**
     * @brief Get the detected FrameView version
     * @return Version string, or empty if not determined
     */
    std::string getVersion() const { return m_version; }
    
    /**
     * @brief Find the latest CSV file generated for a specific application
     * @param appName The application name to search for (e.g., "Cyberpunk2077.exe")
     * @return Path to the CSV file, or empty path if not found
     * 
     * Searches the output directory for CSV files containing the app name.
     * Returns the most recently modified file that hasn't been consumed.
     */
    std::filesystem::path findLatestCsvForApp(const std::string& appName);
    
    /**
     * @brief Mark a CSV file as consumed so it won't be returned again
     * @param path Path to the CSV file to mark as consumed
     * 
     * After consuming a CSV, subsequent calls to findLatestCsvForApp() 
     * will not return that file, allowing multiple test runs with the 
     * same application to each get their own CSV.
     */
    void notifyCsvConsumed(const std::filesystem::path& path);

private:
    FrameViewRunner() = default;

    std::filesystem::path findFrameViewInstallation();
    void killFrameViewProcesses();
    bool launchPresentMon(std::string& outError);

    std::filesystem::path m_installPath;         ///< FrameView installation path (holds bin\PresentMon_x64.exe)
    std::string m_version;                       ///< FrameView version
    std::filesystem::path m_outputDirectory;     ///< Where PresentMon writes CSVs
    std::set<std::filesystem::path> m_consumedCsvs;  ///< CSVs already consumed
    mutable std::mutex m_csvMutex;                   ///< Guards m_consumedCsvs
};
