#pragma once

#include <filesystem>
#include <string>
#include <set>

/**
 * @class FrameViewRunner
 * @brief Manages FrameView lifecycle for automated performance testing
 * 
 * This class handles:
 * - Auto-detecting FrameView installation
 * - Creating an isolated copy for testing
 * - Configuring output directory
 * - Starting/stopping FrameView processes
 * - Finding CSV log files generated by FrameView
 * 
 * Usage:
 *   {
 *       FrameViewRunner frameView;
 *       if (!frameView.isValid()) {
 *           // Handle error
 *       }
 *       
 *       // Run tests...
 *       auto csv = frameView.findLatestCsvForApp("MyGame.exe");
 *       frameView.notifyCsvConsumed(csv);
 *   }  // Destructor cleans up FrameView processes
 */
class FrameViewRunner
{
public:
    /**
     * @brief Constructor - finds FrameView, creates isolated copy, and starts it
     * 
     * On construction:
     * 1. Kills any existing FrameView processes
     * 2. Finds FrameView installation (registry or common paths)
     * 3. Copies FrameView to temp directory for isolation
     * 4. Configures Settings.ini with output directory
     * 5. Launches FrameView_x64.exe
     */
    FrameViewRunner();
    
    /**
     * @brief Destructor - kills FrameView processes
     */
    ~FrameViewRunner();
    
    // Non-copyable, non-movable
    FrameViewRunner(const FrameViewRunner&) = delete;
    FrameViewRunner& operator=(const FrameViewRunner&) = delete;
    FrameViewRunner(FrameViewRunner&&) = delete;
    FrameViewRunner& operator=(FrameViewRunner&&) = delete;
    
    /**
     * @brief Check if FrameView was successfully started
     * @return true if FrameView is running and ready
     */
    bool isValid() const { return m_valid; }
    
    /**
     * @brief Get error message if isValid() returns false
     * @return Error description
     */
    std::string getError() const { return m_error; }
    
    /**
     * @brief Get the detected FrameView installation path
     * @return Path to FrameView installation, or empty if not found
     */
    std::filesystem::path getInstallPath() const { return m_installPath; }
    
    /**
     * @brief Get the detected FrameView version
     * @return Version string, or empty if not found
     */
    std::string getVersion() const { return m_version; }
    
    /**
     * @brief Find the latest CSV file generated for a specific application
     * @param appName The application name to search for (e.g., "Cyberpunk2077.exe")
     * @return Path to the CSV file, or empty path if not found
     * 
     * Searches the output directory for CSV files containing the app name.
     * Returns the most recently modified file that hasn't been consumed.
     */
    std::filesystem::path findLatestCsvForApp(const std::string& appName);
    
    /**
     * @brief Mark a CSV file as consumed so it won't be returned again
     * @param path Path to the CSV file to mark as consumed
     * 
     * After consuming a CSV, subsequent calls to findLatestCsvForApp() 
     * will not return that file, allowing multiple test runs with the 
     * same application to each get their own CSV.
     */
    void notifyCsvConsumed(const std::filesystem::path& path);

private:
    /**
     * @brief Find FrameView installation path
     * @return Path to FrameView installation, or empty if not found
     */
    std::filesystem::path findFrameViewInstallation();
    
    /**
     * @brief Kill all running FrameView-related processes
     */
    void killFrameViewProcesses();
    
    /**
     * @brief Copy FrameView installation to isolated temp directory
     * @param sourceDir Source FrameView installation path
     * @return true if successful
     */
    bool prepareFrameViewCopy(const std::filesystem::path& sourceDir);
    
    /**
     * @brief Modify Settings.ini in the copy to set output directory
     * @return true if successful
     */
    bool modifyIniFile();
    
    /**
     * @brief Launch FrameView_x64.exe from the copy
     * @return true if successful
     */
    bool launchFrameView();

    std::filesystem::path m_installPath;         ///< Original FrameView installation path
    std::string m_version;                       ///< FrameView version
    std::filesystem::path m_frameViewCopyPath;   ///< Path to copied FrameView
    std::filesystem::path m_outputDirectory;     ///< Where CSVs are written
    std::set<std::filesystem::path> m_consumedCsvs;  ///< CSVs already consumed
    bool m_valid = false;
    std::string m_error;
};
