# GenerateEmbeddedSpirv.ps1
# Compiles every .hlsl in this directory to SPIR-V via DXC and emits a
# single C++ header containing the bytecode as constexpr uint32_t arrays
# plus a name->(ptr,bytes) lookup. Skips work if the header is already
# up-to-date relative to all inputs (HLSL files, this script, and DXC).
#
# Shader profile is inferred from filename suffix:
#   *VS.hlsl -> vs_6_0
#   *PS.hlsl -> ps_6_0
#   *CS.hlsl -> cs_6_0

param(
    [string]$ShaderDir = $PSScriptRoot,
    [string]$OutputFile = (Join-Path $PSScriptRoot "..\internal\g_EmbeddedSpirvShaders.h")
)

if (-not $env:VULKAN_SDK) {
    Write-Error "VULKAN_SDK environment variable not set."
    exit 1
}
$dxc = Join-Path $env:VULKAN_SDK 'Bin\dxc.exe'
if (-not (Test-Path $dxc)) {
    Write-Error "dxc.exe not found at $dxc"
    exit 1
}

$hlslFiles = Get-ChildItem -Path $ShaderDir -Filter "*.hlsl" | Sort-Object Name
if ($hlslFiles.Count -eq 0) {
    Write-Error "No .hlsl files found in $ShaderDir"
    exit 1
}

# Up-to-date check: skip if output is newer than every input.
if (Test-Path $OutputFile) {
    $outputTime    = (Get-Item $OutputFile).LastWriteTime
    $newestShader  = ($hlslFiles | Sort-Object LastWriteTime -Descending | Select-Object -First 1).LastWriteTime
    $scriptTime    = (Get-Item $PSCommandPath).LastWriteTime
    $dxcTime       = (Get-Item $dxc).LastWriteTime
    $newestInput   = @($newestShader, $scriptTime, $dxcTime) | Sort-Object -Descending | Select-Object -First 1
    if ($outputTime -ge $newestInput) {
        Write-Host "g_EmbeddedSpirvShaders.h is up-to-date, skipping generation."
        exit 0
    }
}

function Get-Profile([string]$name) {
    if ($name.EndsWith("VS")) { return "vs_6_0" }
    if ($name.EndsWith("PS")) { return "ps_6_0" }
    if ($name.EndsWith("CS")) { return "cs_6_0" }
    return $null
}

$tempDir = Join-Path $env:TEMP "visLib_spirv_gen"
New-Item -ItemType Directory -Force -Path $tempDir | Out-Null

$shaders = @()
foreach ($file in $hlslFiles) {
    $name = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
    $profile = Get-Profile $name
    if (-not $profile) {
        Write-Error "Cannot infer shader profile from name '$name' (expected suffix VS/PS/CS)."
        exit 1
    }
    $spvPath = Join-Path $tempDir "$name.spv"
    # -fvk-use-dx-layout keeps cbuffer member alignment matching D3D12's packing
    # so the same CPU-side structs work for both backends. -fvk-use-dx-position-w
    # avoids the SV_Position.w flip that's a footgun when porting D3D shaders.
    & $dxc -spirv -fvk-use-dx-layout -fvk-use-dx-position-w `
           -T $profile -E main $file.FullName -Fo $spvPath 2>&1 | Out-Null
    if ($LASTEXITCODE -ne 0) {
        Write-Error "DXC failed for $($file.Name)"
        exit 1
    }
    $bytes = [System.IO.File]::ReadAllBytes($spvPath)
    if ($bytes.Length -eq 0 -or ($bytes.Length % 4) -ne 0) {
        Write-Error "SPIR-V output for $name is empty or not 4-byte aligned (size=$($bytes.Length))"
        exit 1
    }
    $words = New-Object 'uint[]' ($bytes.Length / 4)
    [Buffer]::BlockCopy($bytes, 0, $words, 0, $bytes.Length)
    $shaders += [PSCustomObject]@{ Name = $name; Words = $words; Profile = $profile }
}

# Emit the header.
$lines = @()
$lines += "#pragma once"
$lines += ""
$lines += "#ifdef _WIN32"
$lines += ""
$lines += "// AUTO-GENERATED by GenerateEmbeddedSpirv.ps1 - do not edit manually."
$lines += "// Edit the .hlsl source files instead and rebuild."
$lines += ""
$lines += "#include <cstdint>"
$lines += "#include <cstddef>"
$lines += "#include <string>"
$lines += "#include <unordered_map>"
$lines += "#include <utility>"
$lines += ""
$lines += "namespace visLib {"
$lines += "namespace EmbeddedSpirvShaders {"
$lines += ""

foreach ($s in $shaders) {
    $lines += "// $($s.Name) ($($s.Profile), $($s.Words.Length) words)"
    $lines += "inline constexpr uint32_t $($s.Name)[] = {"
    for ($i = 0; $i -lt $s.Words.Length; $i += 8) {
        $end = [Math]::Min($i + 8, $s.Words.Length)
        $chunk = @()
        for ($j = $i; $j -lt $end; $j++) {
            $chunk += ("0x{0:X8}u" -f $s.Words[$j])
        }
        $lines += "    " + ($chunk -join ', ') + ","
    }
    $lines += "};"
    $lines += ""
}

$lines += "// Look up embedded SPIR-V bytecode by name."
$lines += "// Returns {pointer, byte size} suitable for VkShaderModuleCreateInfo,"
$lines += "// or {nullptr, 0} if no shader with that name exists."
$lines += "inline std::pair<const uint32_t*, std::size_t> getShader(const std::string& name) {"
$lines += "    static const std::unordered_map<std::string, std::pair<const uint32_t*, std::size_t>> shaders = {"
foreach ($s in $shaders) {
    $lines += "        { `"$($s.Name)`", { $($s.Name), sizeof($($s.Name)) } },"
}
$lines += "    };"
$lines += "    auto it = shaders.find(name);"
$lines += "    return (it != shaders.end()) ? it->second : std::pair<const uint32_t*, std::size_t>(nullptr, 0);"
$lines += "}"
$lines += ""
$lines += "} // namespace EmbeddedSpirvShaders"
$lines += "} // namespace visLib"
$lines += ""
$lines += "#endif // _WIN32"

$output = $lines -join "`r`n"
Set-Content -Path $OutputFile -Value $output -NoNewline -Encoding UTF8
Write-Host "Generated g_EmbeddedSpirvShaders.h from $($shaders.Count) shader(s)."
