# GenerateEmbeddedShaders.ps1
# Reads all .hlsl files in this directory and generates EmbeddedShaders.h
# Skips generation if the header is already up-to-date.

param(
    [string]$ShaderDir = $PSScriptRoot,
    [string]$OutputFile = (Join-Path $PSScriptRoot "..\internal\g_EmbeddedShaders.h")
)

$hlslFiles = Get-ChildItem -Path $ShaderDir -Filter "*.hlsl" | Sort-Object Name

if ($hlslFiles.Count -eq 0) {
    Write-Error "No .hlsl files found in $ShaderDir"
    exit 1
}

# Check if output is already up-to-date
if (Test-Path $OutputFile) {
    $outputTime = (Get-Item $OutputFile).LastWriteTime
    $newestShader = ($hlslFiles | Sort-Object LastWriteTime -Descending | Select-Object -First 1).LastWriteTime
    $scriptTime = (Get-Item $PSCommandPath).LastWriteTime
    $newestInput = @($newestShader, $scriptTime) | Sort-Object -Descending | Select-Object -First 1
    if ($outputTime -ge $newestInput) {
        Write-Host "g_EmbeddedShaders.h is up-to-date, skipping generation."
        exit 0
    }
}

$lines = @()
$lines += "#pragma once"
$lines += ""
$lines += "#ifdef _WIN32"
$lines += ""
$lines += "// AUTO-GENERATED by GenerateEmbeddedShaders.ps1 - do not edit manually."
$lines += "// Edit the .hlsl source files instead and rebuild."
$lines += ""
$lines += "#include <string>"
$lines += "#include <unordered_map>"
$lines += ""
$lines += "namespace visLib {"
$lines += "namespace EmbeddedShaders {"
$lines += ""

foreach ($file in $hlslFiles) {
    $name = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
    $content = Get-Content -Path $file.FullName -Raw
    $lines += "inline const char* $name = R`"HLSL("
    $lines += $content.TrimEnd()
    $lines += ")HLSL`";"
    $lines += ""
}

$lines += "// Look up embedded shader source by name (e.g. `"VertexShader`", `"QRCodePixelShader`")"
$lines += "inline const char* getSource(const std::string& name)"
$lines += "{"
$lines += "    static const std::unordered_map<std::string, const char*> shaders = {"

foreach ($file in $hlslFiles) {
    $name = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
    $pad = " " * (20 - $name.Length)
    if ($pad.Length -lt 1) { $pad = " " }
    $lines += "        { `"$name`",$pad$name },"
}

$lines += "    };"
$lines += "    auto it = shaders.find(name);"
$lines += "    return (it != shaders.end()) ? it->second : nullptr;"
$lines += "}"
$lines += ""
$lines += "} // namespace EmbeddedShaders"
$lines += "} // namespace visLib"
$lines += ""
$lines += "#endif // _WIN32"

$output = $lines -join "`r`n"
Set-Content -Path $OutputFile -Value $output -NoNewline -Encoding UTF8
Write-Host "Generated g_EmbeddedShaders.h from $($hlslFiles.Count) shader(s)."
